app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


Route::group(['middleware' => ['web']], function () {

	Route::get('/','HomeController@index');
    Route::auth();
	Route::get('/home', 'HomeController@index');
	Route::get('books/{book}/download',[
		'middleware'=>['auth','role:member'],
		'as'=>'books.download',
		'uses'=>'BooksController@download']);
	Route::get('books/{book}/baca',[
		'middleware'=>['auth','role:member'],
		'as'=>'books.baca',
		'uses'=>'BooksController@baca']);
	Route::get('settings/profile','SettingsController@profile');
	Route::get('settings/profile/edit','SettingsController@editProfile');
	Route::post('settings/profile/','SettingsController@updateProfile');
	Route::get('settings/password','SettingsController@editPassword');
	Route::post('settings/password','SettingsController@updatePassword');
	Route::get('auth/verify/{token}', 'Auth\AuthController@verify');
	Route::get('auth/send-verification', 'Auth\AuthController@sendVerification');
	Route::get('bukusaya', ['uses'=>'HomeController@bukusaya', 'as'=>'bukusaya']);
	//Route::get('books/{book}/show',[
	//	'middleware'=>['auth','role:member'],
	//	'as'=>'books.show',
	//	'uses'=>'GuestController@show']);
	Route::get('books/{book}/createcover', [
		'middleware'=>['auth','role:member'],
		'as'=>'books.createcover',
		'uses'=>'GuestController@createcover']);
	

	Route::group(['middleware' => 'auth'], function() {

	Route::resource('books', 'GuestController');
	

	});


//Route Admin
	Route::group(['prefix'=>'admin', 'middleware'=>['auth', 'role:admin']], function () {
		Route::resource('books', 'BooksController');
		Route::resource('members', 'MembersController', [
            'only'=>['index', 'show', 'destroy']
        ]);

		});


  });

app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    //
    protected $fillable = ['title','user_id', 'description'];

    public function user(){
    	return $this->belongsTo('App\User');
    }
}

app/Http/Controllers/BooksController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use Yajra\Datatables\Html\Builder;
use Yajra\Datatables\Datatables;
use App\Book;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\File;
use App\Http\Controllers\Controller;

class BooksController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request, Builder $htmlBuilder)
    {
        //
        if ($request->ajax()) {
            $books = Book::select(['id','title']);
            return Datatables::of($books)
                ->addColumn('action', function($book){
                    return view('datatable._action', [
                        'model'           => $book,
                        'form_url'        => route('admin.books.destroy', $book->id),
                        'confirm_message' => 'Yakin mau menghapus ' . $book->title . '?'
                    ]);
                })->make(true);
        }

        $html = $htmlBuilder
            ->addColumn(['data' => 'title', 'name'=>'title', 'title'=>'Judul'])
            ->addColumn(['data' => 'action', 'name'=>'action', 'title'=>'', 'orderable'=>false, 'searchable'=>false]);

        return view('books.index')->with(compact('html'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('books.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
         $this->validate($request, [
            'title'     => 'required|unique:books,title',
        //    'user_id'   => 'required|exists:users,id',
          //  'cover'     => 'image|max:2048',
            'file'     => 'file|max:200480',
            //'description' => 'required'
        ]);


        $book = Book::create([
            $request->except('file'),
            $request->except('cover'),
            'user_id' => Auth::user()->id,
            'title' =>$request-> input('title'),
            'description' => $request->input('description')
            ]);

        // isi field cover jika ada cover yang diupload
        if ($request->hasFile('file')) {
            $uploaded_file = $request->file('file');

            // mengambil extension file
            $extension = $uploaded_file->getClientOriginalExtension();

            // membuat nama file random dengan extension
            $filename = time() . '.' . $extension;

            // memindahkan file ke folder public/img
            $destinationPath = public_path() . DIRECTORY_SEPARATOR . 'file';
            $uploaded_file->move($destinationPath, $filename);

            // mengisi field cover di book dengan filename yang baru dibuat
            $book->file = $filename;
            $book->save();
        }
        if ($request->hasFile('cover')) {
            $uploaded_cover = $request->file('cover');

            // mengambil extension file
            $extension = $uploaded_cover->getClientOriginalExtension();

            // membuat nama file random dengan extension
            $filename = md5(time()) . '.' . $extension;

            // memindahkan file ke folder public/img
            $destinationPath = public_path() . DIRECTORY_SEPARATOR . 'img';
            $uploaded_cover->move($destinationPath, $filename);

            // mengisi field cover di book dengan filename yang baru dibuat
            $book->cover = $filename;
            $book->save();
        }

        Session::flash("flash_notification", [
            "level"=>"success",
            "message"=>"Berhasil menyimpan $book->title"
        ]);

        return redirect()->route('admin.books.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        $book = Book::find($id);
        $cover = $book->cover;
        $file = $book->file;
        if(!$book->delete()) return redirect()->back();

        // handle hapus buku via ajax
        if ($request->ajax()) return response()->json(['id' => $id]);

        // hapus cover lama, jika ada
        if ($cover) {
            $old_cover = $book->cover;
            $filepath = public_path() . DIRECTORY_SEPARATOR . 'img'
                . DIRECTORY_SEPARATOR . $book->cover;

            try {
                File::delete($filepath);
            } catch (FileNotFoundException $e) {
                // File sudah dihapus/tidak ada
            }
        }

        if ($file) {
            $old_file = $book->file;
            $filepath = public_path() . DIRECTORY_SEPARATOR . 'file'
                . DIRECTORY_SEPARATOR . $book->file;

            try {
                File::delete($filepath);
            } catch (FileNotFoundException $e) {
                // File sudah dihapus/tidak ada
            }
        }

        Session::flash("flash_notification", [
            "level"=>"success",
            "message"=>"Buku berhasil dihapus"
        ]);

        return redirect()->route('admin.books.index');
    }

    public function baca($id){
        $book = Book::find($id);
        $file = $book->file;
        $filepath = public_path() . DIRECTORY_SEPARATOR . 'file'
            . DIRECTORY_SEPARATOR . $book->file;
        return response::make(file_get_contents($filepath), 200, [
            'Content-Type'=>'application/pdf',
            'Content-Disposition'=>'inline;filename="'.$file.'"']);
    }


    public function download($id){
        $book = Book::find($id);
        $file = $book->file;
        $filepath = public_path() . DIRECTORY_SEPARATOR . 'file'
            . DIRECTORY_SEPARATOR . $book->file;
        return response()->download($filepath);
    }


    
}

resources/views/books/_form.blade.php
<div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
  {!! Form::label('title', 'Judul', ['class'=>'col-md-2 control-label']) !!}
  <div class="col-md-4">
    {!! Form::text('title', null, ['class'=>'form-control']) !!}
    {!! $errors->first('title', '<p class="help-block">:message</p>') !!}
  </div>
</div>


<div class="form-group{{ $errors->has('file') ? ' has-error' : '' }}">
  {!! Form::label('file', 'File', ['class'=>'col-md-2 control-label']) !!}
  <div class="col-md-4">
    {!! Form::file('file') !!}
    @if (isset($book) && $book->file)
      <p>
      {!! Html::image(asset('file/'.$book->file), null, ['class'=>'form-control']) !!}
      </p>
    @endif
    {!! $errors->first('file', '<p class="help-block">:message</p>') !!}
  </div>
</div>

<div class="form-group{{ $errors->has('cover') ? ' has-error' : '' }}">
  {!! Form::label('cover', 'Cover', ['class'=>'col-md-2 control-label']) !!}
  <div class="col-md-4">
    {!! Form::file('cover') !!}
    @if (isset($book) && $book->cover)
      <p>
      {!! Html::image(asset('img/'.$book->cover), null, ['class'=>'img-rounded']) !!}
      </p>
    @endif
    {!! $errors->first('cover', '<p class="help-block">:message</p>') !!}
  </div>
</div>


<div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
  {!! Form::label('description', 'Deskripsi', ['class'=>'col-md-2 control-label']) !!}
  <div class="col-md-4">
    {!! Form::textArea('description', null, ['class'=>'form-control']) !!}
    {!! $errors->first('description', '<p class="help-block">:message</p>') !!}
  </div>
</div>

<div class="form-group">
  <div class="col-md-4 col-md-offset-2">
    {!! Form::submit('Simpan', ['class'=>'btn btn-primary']) !!}
  </div>
</div>

resources/views/books/create.blade.php
@extends('layouts.template')

@section('content')
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <ul class="breadcrumb">
          <li><a href="{{ url('/home') }}">Dashboard</a></li>
          <li><a href="{{ url('/admin/books') }}">Buku</a></li>
          <li class="active">Tambah Buku</li>
        </ul>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h2 class="panel-title">Tambah Buku</h2>
          </div>

          <div class="panel-body">            
                {!! Form::open(['url' => route('admin.books.store'), 
                  'method' => 'post', 'files'=>'true', 'class'=>'form-horizontal']) !!}
                  @include('books._form')
                {!! Form::close() !!}
          </div>
              
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/books/createguest.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <ul class="breadcrumb">
          <li><a href="{{ url('/home') }}">Dashboard</a></li>
          <li><a href="{{ url('/books') }}">Buku</a></li>
          <li class="active">Tambah Buku</li>
        </ul>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h2 class="panel-title">Tambah Buku</h2>
          </div>

          <div class="panel-body">            
                {!! Form::open(['url' => route('guest.store'), 
                  'method' => 'post', 'files'=>'true', 'class'=>'form-horizontal']) !!}
                  @include('books._form')
                {!! Form::close() !!}
          </div>
              
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/books/index.blade.php
@extends('layouts.dashboard')

@section('content')
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <ul class="breadcrumb">
          <li><a href="{{ url('/home') }}">Dashboard</a></li>
          <li class="active">Buku</li>
        </ul>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h2 class="panel-title">Buku</h2>
          </div>

          <div class="panel-body">
            <p> 
            <a class="btn btn-primary" href="{{ url('/admin/books/create') }}">Tambah</a> 
            </p>
            {!! $html->table(['class'=>'table-striped']) !!}
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection

@section('scripts')
  {!! $html->scripts() !!}
@endsection

resources/views/books/member.blade.php
@extends('layouts.dashboard')

@section('content')
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <ul class="breadcrumb">
          <li><a href="{{ url('/home') }}">Dashboard</a></li>
          <li class="active">Buku</li>
        </ul>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h2 class="panel-title">Buku</h2>
          </div>

          <div class="panel-body">
            <p> 
            <a class="btn btn-primary" href="{{ url('/books/create') }}">Tambah</a> 
            </p>
            {!! $html->table(['class'=>'table-striped']) !!}
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection

@section('scripts')
  {!! $html->scripts() !!}
@endsection

resources/views/books/show.blade.php
@extends('layouts.dashboard')

@section('content')
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <ul class="breadcrumb">
          <li><a href="{{ url('/home') }}">Dashboard</a></li>
          <li class="active">Detail {{ $buku->title }}</li>
        </ul>
        <div class="panel panel-default">
          <div id="all">
  <div class="container">
    <div class="row" id="productMain">
      <div class="col-sm-6">
        <div id="mainImage">
          <img src="{{asset('img/'.$buku->cover)}}" width="250" height="250" alt="" class="img-responsive">
        </div>
      </div>
      
      <div class="col-sm-6">
        <div class="box" id="details">
          
          <h3>Ebook detail</h3>
          <h4>{{ $buku->title }}</h4>
          
          <blockquote>
            <p><em>{{ $buku->description }}</em></p>
          </blockquote>
          <a class="btn btn-xs btn-primary" href="{{url('/books/'.$buku->id.'/download')}}">Download</a>
          <hr>
          
        </div>
      </div>
    </div>
  </div>
</div>
<table>
  <tr></tr>
</table>



@endsection