app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


Route::group(['middleware' => ['web']], function () {

	Route::get('/','HomeController@index');
    Route::auth();
	Route::get('/home', 'HomeController@index');
	Route::get('books/{book}/download',[
		'middleware'=>['auth','role:member'],
		'as'=>'books.download',
		'uses'=>'BooksController@download']);
	Route::get('books/{book}/baca',[
		'middleware'=>['auth','role:member'],
		'as'=>'books.baca',
		'uses'=>'BooksController@baca']);
	Route::get('settings/profile','SettingsController@profile');
	Route::get('settings/profile/edit','SettingsController@editProfile');
	Route::post('settings/profile/','SettingsController@updateProfile');
	Route::get('settings/password','SettingsController@editPassword');
	Route::post('settings/password','SettingsController@updatePassword');
	Route::get('auth/verify/{token}', 'Auth\AuthController@verify');
	Route::get('auth/send-verification', 'Auth\AuthController@sendVerification');
	Route::get('bukusaya', ['uses'=>'HomeController@bukusaya', 'as'=>'bukusaya']);
	//Route::get('books/{book}/show',[
	//	'middleware'=>['auth','role:member'],
	//	'as'=>'books.show',
	//	'uses'=>'GuestController@show']);
	Route::get('books/{book}/createcover', [
		'middleware'=>['auth','role:member'],
		'as'=>'books.createcover',
		'uses'=>'GuestController@createcover']);
	

	Route::group(['middleware' => 'auth'], function() {

	Route::resource('books', 'GuestController');
	

	});


//Route Admin
	Route::group(['prefix'=>'admin', 'middleware'=>['auth', 'role:admin']], function () {
		Route::resource('books', 'BooksController');
		Route::resource('members', 'MembersController', [
            'only'=>['index', 'show', 'destroy']
        ]);

		});


  });

app/Http/Controllers/GuestController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use Yajra\Datatables\Html\Builder;
use Yajra\Datatables\Datatables;
use App\Book;
use Illuminate\Support\Facades\Auth;
use Entrust;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\File;


class GuestController extends Controller
{
    //

    public function home(){
        return view('auth.login');
    }


    public function index(Request $request, Builder $htmlBuilder)
    {
    	if ($request->ajax()) {
            $books = Book::select(['id','title']);
            return Datatables::of($books)
                ->addColumn('action', function($book){
                 //  if (Entrust::hasRole('admin')) return'';
           //        return '<a class="btn btn-xs btn-primary" href="'.route('books.download',$book->id).'">Download</a>';
                   return '<a class="btn btn-xs btn-primary" href="'.route('books.show',$book->id).'">Detail</a>';
                })->make(true);
    	}

    	$html = $htmlBuilder
            ->addColumn(['data' => 'title', 'name'=>'title', 'title'=>'Judul'])
            ->addColumn(['data' => 'action', 'name'=>'action', 'title'=>'', 'orderable'=>false, 'searchable'=>false]);

        return view('guest.index')->with(compact('html'));
	}


/*	 public function books(Request $request, Builder $htmlBuilder)
    {
        //
        if ($request->ajax()) {
            $books = Book::select(['id','title']);
            return Datatables::of($books)
                ->addColumn('action', function($book){
                    return view('datatable._action', [
                        'model'           => $book,
                        'form_url'        => route('books.destroy', $book->id),
                        'confirm_message' => 'Yakin mau menghapus ' . $book->title . '?'
                    ]);
                })->make(true);
        }

        $html = $htmlBuilder
            ->addColumn(['data' => 'title', 'name'=>'title', 'title'=>'Judul'])
            ->addColumn(['data' => 'action', 'name'=>'action', 'title'=>'', 'orderable'=>false, 'searchable'=>false]);

        return view('guest.tmbhbook')->with(compact('html'));
    }
*/
     public function create()
    {
        //
        return view('guest.create');
    }

     public function store(Request $request)
    {
        //
        $this->validate($request, [
            'title'     => 'required|unique:books,title',
        //    'user_id'   => 'required|exists:users,id',
          //  'cover'     => 'image|max:2048',
            'file'     => 'file|max:200480',
           // 'description' => 'required'
        ]);


        $book = Book::create([
            $request->except('file'),
            $request->except('cover'),
            'user_id' => Auth::user()->id,
            'title' =>$request-> input('title'),
            'description' => $request->input('description')
            ]);

        // isi field cover jika ada cover yang diupload
        if ($request->hasFile('file')) {
            $uploaded_file = $request->file('file');

            // mengambil extension file
            $extension = $uploaded_file->getClientOriginalExtension();

            // membuat nama file random dengan extension
            $filename = time() . '.' . $extension;

            // memindahkan file ke folder public/img
            $destinationPath = public_path() . DIRECTORY_SEPARATOR . 'file';
            $uploaded_file->move($destinationPath, $filename);

            // mengisi field cover di book dengan filename yang baru dibuat
            $book->file = $filename;
            $book->save();
        }
        if ($request->hasFile('cover')) {
            $uploaded_cover = $request->file('cover');

            // mengambil extension file
            $extension = $uploaded_cover->getClientOriginalExtension();

            // membuat nama file random dengan extension
            $filename = md5(time()) . '.' . $extension;

            // memindahkan file ke folder public/img
            $destinationPath = public_path() . DIRECTORY_SEPARATOR . 'img';
            $uploaded_cover->move($destinationPath, $filename);

            // mengisi field cover di book dengan filename yang baru dibuat
            $book->cover = $filename;
            $book->save();
        }

        Session::flash("flash_notification", [
            "level"=>"success",
            "message"=>"Berhasil menyimpan $book->title"
        ]);

        return redirect()->route('books.create');
    }

    public function destroy(Request $request, $id)
    {
        $book = Book::find($id);
        $cover = $book->cover;
        $file = $book->file;
        if(!$book->delete()) return redirect()->back();

        // handle hapus buku via ajax
        if ($request->ajax()) return response()->json(['id' => $id]);

        // hapus cover lama, jika ada
        if ($cover) {
            $old_cover = $book->cover;
            $filepath = public_path() . DIRECTORY_SEPARATOR . 'img'
                . DIRECTORY_SEPARATOR . $book->cover;

            try {
                File::delete($filepath);
            } catch (FileNotFoundException $e) {
                // File sudah dihapus/tidak ada
            }
        }
        

        if ($file) {
            $old_file = $book->file;
            $filepath = public_path() . DIRECTORY_SEPARATOR . 'file'
                . DIRECTORY_SEPARATOR . $book->file;

            try {
                File::delete($filepath);
            } catch (FileNotFoundException $e) {
                // File sudah dihapus/tidak ada
            }
        }

        Session::flash("flash_notification", [
            "level"=>"success",
            "message"=>"Buku berhasil dihapus"
        ]);
        return redirect()->back();
    }


    public function edit($id){
         $book = Book::find($id);
        return view('guest.edit')->with(compact('book'));

    }

        //
    public function update(UpdateBookRequest $request, $id){

        $book = Book::find($id);
        if(!$book->update($request->all())) return redirect()->back();

        if ($request->hasFile('cover')) {
            $filename = null;
            $uploaded_cover = $request->file('cover');
            $extension = $uploaded_cover->getClientOriginalExtension();

            // membuat nama file random dengan extension
            $filename = md5(time()) . '.' . $extension;
            $destinationPath = public_path() . DIRECTORY_SEPARATOR . 'img';

            // memindahkan file ke folder public/img
            $uploaded_cover->move($destinationPath, $filename);

            // hapus cover lama, jika ada
            if ($book->cover) {
                $old_cover = $book->cover;
                $filepath = public_path() . DIRECTORY_SEPARATOR . 'img'
                    . DIRECTORY_SEPARATOR . $book->cover;

                try {
                    File::delete($filepath);
                } catch (FileNotFoundException $e) {
                    // File sudah dihapus/tidak ada
                }
            }

            // ganti field cover dengan cover yang baru
            $book->cover = $filename;
            $book->save();
        }
        if ($request->hasFile('file')) {
            $uploaded_file = $request->file('file');

            // mengambil extension file
            $extension = $uploaded_file->getClientOriginalExtension();

            // membuat nama file random dengan extension
            $filename = time() . '.' . $extension;

            // memindahkan file ke folder public/img
            $destinationPath = public_path() . DIRECTORY_SEPARATOR . 'file';
            $uploaded_file->move($destinationPath, $filename);

            if ($book->file) {
                $old_file = $book->file;
                $filepath = public_path() . DIRECTORY_SEPARATOR . 'file'
                    . DIRECTORY_SEPARATOR . $book->file;

                try {
                    File::delete($filepath);
                } catch (FileNotFoundException $e) {
                    // File sudah dihapus/tidak ada
                }
            }

            // mengisi field cover di book dengan filename yang baru dibuat
            $book->file = $filename;
            $book->save();
        }

        Session::flash("flash_notification", [
            "level"=>"success",
            "message"=>"Berhasil menyimpan $book->title"
        ]);
    }


     public function download($id){
        $book = Book::find($id);
        $file = $book->file;
        $filepath = public_path() . DIRECTORY_SEPARATOR . 'file'
            . DIRECTORY_SEPARATOR . $book->file;
        return response()->download($filepath);
    }



     public function show($id)
    {
        //
        $buku = Book::find($id);
        return view('books.show', compact('buku', 'slug'));
  //      return '<a class="btn btn-xs btn-primary" href="'.route('books.download',$book->id).'">Download</a>';
    }

}

resources/views/guest/_form.blade.php
<div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
  {!! Form::label('title', 'Judul', ['class'=>'col-md-2 control-label']) !!}
  <div class="col-md-4">
    {!! Form::text('title', null, ['class'=>'form-control']) !!}
    {!! $errors->first('title', '<p class="help-block">:message</p>') !!}
  </div>
</div>


<div class="form-group{{ $errors->has('file') ? ' has-error' : '' }}">
  {!! Form::label('file', 'File', ['class'=>'col-md-2 control-label']) !!}
  <div class="col-md-4">
    {!! Form::file('file') !!}
   
    {!! $errors->first('file', '<p class="help-block">:message</p>') !!}
  </div>
</div>

<div class="form-group{{ $errors->has('cover') ? ' has-error' : '' }}">
  {!! Form::label('cover', 'Cover', ['class'=>'col-md-2 control-label']) !!}
  <div class="col-md-4">
    {!! Form::file('cover') !!}
    @if (isset($book) && $book->cover)
      <p>
      {!! Html::image(asset('img/'.$book->cover), null, ['class'=>'img-rounded']) !!}
      </p>
    @endif
    {!! $errors->first('cover', '<p class="help-block">:message</p>') !!}
  </div>
</div>


<div class="form-group{{ $errors->has('descrption') ? ' has-error' : '' }}">
  {!! Form::label('description', 'Deskripsi', ['class'=>'col-md-2 control-label']) !!}
  <div class="col-md-4">
    {!! Form::textArea('description', null, ['class'=>'form-control']) !!}
    {!! $errors->first('description', '<p class="help-block">:message</p>') !!}
  </div>
</div>

<div class="form-group">
  <div class="col-md-4 col-md-offset-2">
    {!! Form::submit('Simpan', ['class'=>'btn btn-primary']) !!}
  </div>
</div>

resources/views/guest/_formcover.blade.php
<div class="form-group{{ $errors->has('cover') ? ' has-error' : '' }}">
  {!! Form::label('cover', 'Jumlah', ['class'=>'col-md-2 control-label']) !!}
  <div class="col-md-4">
    {!! Form::file('cover') !!}
    @if (isset($book) && $book->cover)
      <p>
      {!! Html::image(asset('img/'.$book->cover), null, ['class'=>'img-rounded']) !!}
      </p>
    @endif
    {!! $errors->first('cover', '<p class="help-block">:message</p>') !!}
  </div>
</div>


<div class="form-group">
  <div class="col-md-4 col-md-offset-2">
    {!! Form::submit('Simpan', ['class'=>'btn btn-primary']) !!}
  </div>
</div>

resources/views/guest/bukusaya.blade.php
@extends('dashboard')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    <table class="table">
              <tbody>
                <tr>
                  <td class="text-muted">Buku saya {{Auth::user()->name}}</td>
                  <td>
                     <ul>
                     
                      @foreach($bukusaya as $book)
                        <tr>
                            <td>{{$book->title}}</td>
                            
                            
                            <td>{{$book->created_at}}</td>

                            <td>
                            <a href="{{route('books.edit', ['book'=>$book->id])}}" class="btn btn-info btn-xs">Edit</a>

                            <form onclick="return confirm('Yakin hapus?')" style="display: inline;" action="{{url('books/'.$book->id)}}" method="post" accept-charset="utf-8">
                    {!! Form::hidden('_method', 'delete') !!}
                    {!!csrf_field()!!}
                    <input type="submit" class="btn btn-danger btn-xs" name="delete" value="Delete">
                    </form></td>
                        </tr>
                        @endforeach
                  
                    </ul>
                  </td>
                </tr>
              </tbody>
            </table>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/guest/create.blade.php
@extends('layouts.dashboard')

@section('content')
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <ul class="breadcrumb">
          <li><a href="{{ url('/home') }}">Dashboard</a></li>
          <li><a href="{{ url('/books') }}">Buku</a></li>
          <li class="active">Tambah Buku</li>
        </ul>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h2 class="panel-title">Tambah Buku</h2>
          </div>

          <div class="panel-body">            
                {!! Form::open(['url' => route('books.store'), 
                  'method' => 'post', 'files'=>'true', 'class'=>'form-horizontal']) !!}
                  @include('guest._form')
                {!! Form::close() !!}
          </div>
              
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/guest/createcover.blade.php
@extends('layouts.app')
@include('layouts.menu')

@section('content')
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <ul class="breadcrumb">
          <li><a href="{{ url('/home') }}">Dashboard</a></li>
          <li><a href="{{ url('/books') }}">Buku</a></li>
          <li class="active">Tambah Buku</li>
        </ul>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h2 class="panel-title">Create Cover</h2>
          </div>

          <div class="panel-body">            
                {!! Form::open(['url' => route('books.store'), 
                  'method' => 'post', 'files'=>'true', 'class'=>'form-horizontal']) !!}
                  @include('guest._form')
                {!! Form::close() !!}
          </div>
              
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/guest/edit.blade.php
@extends('layouts.template')

@section('content')
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <ul class="breadcrumb">
          <li><a href="{{ url('/home') }}">Dashboard</a></li>
          <li><a href="{{ url('/admin/books') }}">Buku</a></li>
          <li class="active">Ubah Buku</li>
        </ul>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h2 class="panel-title">Ubah Buku</h2>
          </div>

          <div class="panel-body">
            {!! Form::model($book, ['url' => route('books.update', $book->id), 
              'method' => 'put', 'files'=>'true', 'class'=>'form-horizontal']) !!}
            @include('guest._form')
            {!! Form::close() !!}
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/guest/index.blade.php
@extends('dashboard')

@section('content')
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h2 class="panel-title">Daftar Buku</h2>
          </div>

          <div class="panel-body">
            {!! $html->table(['class'=>'table-striped']) !!}
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection

@section('scripts')
  {!! $html->scripts() !!}
@endsection

resources/views/guest/tmbhbook.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <ul class="breadcrumb">
          <li><a href="{{ url('/home') }}">Dashboard</a></li>
          <li class="active">Buku</li>
        </ul>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h2 class="panel-title">Buku</h2>
          </div>

          <div class="panel-body">
            <p> 
            <a class="btn btn-primary" href="{{ url('/books/create') }}">Tambah</a> 
            </p>
            {!! $html->table(['class'=>'table-striped']) !!}
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection

@section('scripts')
  {!! $html->scripts() !!}
@endsection